name: CI
on:
  push:
    branches:
    - master
jobs:
  split-upm:
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found
        git subtree split -P "$PKG_ROOT" -b upm
        git checkout upm
      env:
        PKG_ROOT: Packages/PlayerPreferencesEditor/
    - name: rename samples
      run: |
        if [[ -d "Samples" ]]; then
          git mv Samples Samples~
          rm -f Samples.meta
        fi
    - name: copy markdown files
      run: |
        git checkout master README.md
        git checkout master LICENSE.md
        git checkout master CHANGELOG.md
    - name: commit
      run: |
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git commit -am "Restructuring of project for ump"
        git push -f -u origin upm